### ISSUE TITLE
module cross-referecing makes importing fail

### ISSUE THREAD

**Issue by RobinGuillard** [lkorczowski/Tinnitus-n-Sleep#69] opened 2020-05-07 18:08 UTC
Very weird!

When I tried my first pytesting on the new "combine_brux_MEMA" function that I coded, I couldn't even start the pytesting due  to the fact that python no longers succeesses in importing the function "generate_bruxism_report". Here is the error I get:

```
==================ERRORS ==============================
____________________ ERROR collecting tests/test_create_reports.py _______________

ImportError while importing test module 'C:\Users\Zeta\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tests\test_create_reports.py'.

Hint: make sure your test modules/packages have valid Python names.

Traceback:
tests\test_create_reports.py:4: in <module>
    from tinnsleep.create_reports import preprocess, reporting, merge_labels_list
tinnsleep\create_reports.py:11: in <module>
    from tinnsleep.scoring import generate_bruxism_report
tinnsleep\scoring.py:3: in <module>
    from tinnsleep.create_reports import merge_labels_list

E   ImportError: cannot import name 'merge_labels_list' from 'tinnsleep.create_reports' (C:\Users\Zeta\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\create_reports.py)

__________________________ ERROR collecting tests/test_scoring.py _________________________
ImportError while importing test module 'C:\Users\Zeta\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tests\test_scoring.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_scoring.py:3: in <module>
    from tinnsleep.scoring import classif_to_burst, burst_to_episode, create_list_events, rearrange_chronological, \
tinnsleep\scoring.py:3: in <module>
    from tinnsleep.create_reports import merge_labels_list
tinnsleep\create_reports.py:11: in <module>
    from tinnsleep.scoring import generate_bruxism_report

E   ImportError: cannot import name 'generate_bruxism_report' from 'tinnsleep.scoring' (C:\Users\Zeta\Documents\acou_sommeil_HD_ENS\Tinnitus-n-Sleep\tinnsleep\scoring.py)
```

**Comment by RobinGuillard** [comment] 2020-05-07 18:22
Partially solved : 
By putting the function combine_brux_mema in create reports instead of scoring, it works again!

It was maybe due to "intercalling" of functions between files...

**Comment by lkorczowski** [comment] 2020-05-08 08:58
do you have this problem in `master` branch ?

And yes, as I mentioned, we should try to make module as much as possible independent. Cross-reference in module can be problematic, not only because it can throw error but because it is harder to maintain.

Thus, we can think of four levels of hierarchy (each level can call level below) 
- `zero`: utils and validation (toolkit for all other, never import tinnsleep) e.g. tinnsleep.utils, tinnsleep.validation
- `low` : basic operation, should take a minimum of parameters and should be easy to pytest (e.g. tinnsleep.signal, tinnsleep.data). Should avoid importing other tinnsleep except `zero` and NEVER import higher level.
- `middle` : advanced operation, should make complex algorithm but still with a unique purpose. Can call `low` level and below exception made of hierarchical class. e.g. `visualization` , {`burst`, `episode`, `scoring`}, `classification`
- `high` : complex ad-hoc pipelines that are engineered to make process reproductible. Merge plenty of lower level function and dispatch correctly the arguments. At this stage, we can consider that it can actually be difficult to maintain and refactor. Therefore, they should be very rare. e.g. only `create_report`

**Comment by lkorczowski** [comment] 2020-05-08 09:09
therefore there was several problems that need to be fixed:
1. {`burst`, `episode` and `scoring`} are interdependent. We can deal with that by either *option 1* putting then together in a module folder, e.g. `tinnsleep/episode/*` to make explicit their dependency (it is better is there is heriachy between submodules). Or *option 2* merge them in a unique `tinnsleep/episode.py` (it is better when all function are heavily interpendent, it is much harde maintain so also it should be less than 10 functions).

2. removed as much as possible dependencies between modules of same level.

**Comment by lkorczowski** [comment] 2020-05-08 19:44
@RobinGuillard I created an issue that should be dealt in the next sprint #70 

closing

**Closed by lkorczowski** 2020-05-08 19:44 UTC
Labels: bug
